2025-05-15 17:49:45,503 [INFO] spy.SPY003: Espía SPY003 inicializado en posición 40.745751°N, 73.952621°W
2025-05-15 17:49:45,506 [ERROR] spy.SPY003: Error en el espía SPY003: RabbitMQPublisher.__init__() got an unexpected keyword argument 'routing_key'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\spy.py", line 129, in run
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\spy.py", line 48, in connect
    self.comm_client = CommunicationClient(
                       ~~~~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        routing_key="alerts"
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQPublisher.__init__() got an unexpected keyword argument 'routing_key'
2025-05-15 17:49:45,507 [INFO] spy.SPY003: Espía SPY003 finalizado
